<<<<<<< HEAD
theme: jekyll-theme-cayman
=======
<<<<<<< HEAD
theme: jekyll-theme-cayman
=======
theme: jekyll-theme-slate
>>>>>>> d578ea6d50776f9cbc8669f5dbe2b68befd75a62
>>>>>>> 65f2be30dac34c2f471609787752dc9a9bc1328e
